-- init.sql
CREATE DATABASE IF NOT EXISTS hive_data;

USE hive_data;

CREATE TABLE IF NOT EXISTS inout_data (
	entry_id INT(11) NOT NULL,
	group_id INT(11) NOT NULL,
	field1 VARCHAR(255) NULL DEFAULT NULL,
	field2 VARCHAR(255) NULL DEFAULT NULL,
	field3 VARCHAR(255) NULL DEFAULT NULL,
	field4 VARCHAR(255) NULL DEFAULT NULL,
	field5 VARCHAR(255) NULL DEFAULT NULL,
	field6 VARCHAR(255) NULL DEFAULT NULL,
	created_at DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (entry_id, group_id) USING BTREE
);

CREATE TABLE IF NOT EXISTS sensor_data (
	data_id INT(10) NOT NULL,
	hive_id INT(11) NOT NULL,
	temp FLOAT NULL DEFAULT NULL,
	humi FLOAT NULL DEFAULT NULL,
	co2 FLOAT NULL DEFAULT NULL,
	time DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (data_id, hive_id) USING BTREE
);